# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
class information_show_screen(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1022, 595)
        self.columnView = QtWidgets.QColumnView(Form)
        self.columnView.setGeometry(QtCore.QRect(10, 100, 400, 120))
        self.columnView.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 rgba(89, 217, 212, 255),\n"
"                                stop:1 rgba(69, 130, 191, 255));\n"
"border-radius:30px;\n"
"\n"
"")
        self.columnView.setObjectName("columnView")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Samyak Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setGeometry(QtCore.QRect(170, 170, 200, 40))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(89, 217, 212,50);  ")
        self.label.setText("")
        self.label.setObjectName("label")
        self.columnView_2 = QtWidgets.QColumnView(Form)
        self.columnView_2.setGeometry(QtCore.QRect(10, 280, 400, 120))
        self.columnView_2.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 rgba(89, 217, 212, 255),\n"
"                                stop:1 rgba(69, 130, 191, 255));\n"
"border-radius:30px;\n"
"\n"
"")
        self.columnView_2.setObjectName("columnView_2")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(170, 350, 200, 40))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 290, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Samyak Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_3.setGeometry(QtCore.QRect(170, 530, 200, 40))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.columnView_3 = QtWidgets.QColumnView(Form)
        self.columnView_3.setGeometry(QtCore.QRect(10, 460, 400, 120))
        self.columnView_3.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 rgba(89, 217, 212, 255),\n"
"                                stop:1 rgba(69, 130, 191, 255));\n"
"border-radius:30px;\n"
"\n"
"")
        self.columnView_3.setObjectName("columnView_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 470, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Samyak Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(450, 100, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setIconSize(QtCore.QSize(8, 8))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(330, 10, 350, 50))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 170, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setIconSize(QtCore.QSize(8, 8))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 350, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setIconSize(QtCore.QSize(8, 8))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 280, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setIconSize(QtCore.QSize(8, 8))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 530, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setIconSize(QtCore.QSize(8, 8))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 460, 120, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setIconSize(QtCore.QSize(8, 8))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(900, 20, 100, 40))
        self.pushButton_7.setObjectName("pushButton_7")
        self.columnView_4 = QtWidgets.QColumnView(Form)
        self.columnView_4.setGeometry(QtCore.QRect(610, 100, 400, 120))
        self.columnView_4.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 rgba(89, 217, 212, 255),\n"
"                                stop:1 rgba(69, 130, 191, 255));\n"
"border-radius:30px;\n"
"\n"
"")
        self.columnView_4.setObjectName("columnView_4")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_4.setGeometry(QtCore.QRect(770, 170, 200, 40))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(620, 110, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Samyak Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.columnView_5 = QtWidgets.QColumnView(Form)
        self.columnView_5.setGeometry(QtCore.QRect(610, 280, 400, 120))
        self.columnView_5.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 rgba(89, 217, 212, 255),\n"
"                                stop:1 rgba(69, 130, 191, 255));\n"
"border-radius:30px;\n"
"\n"
"")
        self.columnView_5.setObjectName("columnView_5")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_5.setGeometry(QtCore.QRect(770, 350, 200, 40))
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(620, 290, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Samyak Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(620, 470, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Samyak Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_6.setGeometry(QtCore.QRect(770, 530, 200, 40))
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.columnView_6 = QtWidgets.QColumnView(Form)
        self.columnView_6.setGeometry(QtCore.QRect(610, 460, 400, 120))
        self.columnView_6.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 rgba(89, 217, 212, 255),\n"
"                                stop:1 rgba(69, 130, 191, 255));\n"
"border-radius:30px;\n"
"\n"
"")
        self.columnView_6.setObjectName("columnView_6")
        self.label.raise_()
        self.columnView_6.raise_()
        self.columnView_3.raise_()
        self.columnView.raise_()
        self.columnView_2.raise_()
        self.label_2.raise_()
        self.lcdNumber.raise_()
        self.lcdNumber_2.raise_()
        self.label_3.raise_()
        self.lcdNumber_3.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.label_5.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.columnView_4.raise_()
        self.lcdNumber_4.raise_()
        self.label_6.raise_()
        self.columnView_5.raise_()
        self.lcdNumber_5.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.lcdNumber_6.raise_()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "码盘速度显示"))
        self.label_3.setText(_translate("Form", "雷达速度显示"))
        self.label_4.setText(_translate("Form", "GNSS速度显示"))
        self.pushButton.setText(_translate("Form", "打开端口"))
        self.label_5.setText(_translate("Form", "作业数据采集系统"))
        self.pushButton_2.setText(_translate("Form", "关闭端口"))
        self.pushButton_3.setText(_translate("Form", "关闭端口"))
        self.pushButton_4.setText(_translate("Form", "打开端口"))
        self.pushButton_5.setText(_translate("Form", "关闭端口"))
        self.pushButton_6.setText(_translate("Form", "打开端口"))
        self.pushButton_7.setText(_translate("Form", "返回"))
        self.label_6.setText(_translate("Form", "角度显示"))
        self.label_7.setText(_translate("Form", "力F1显示"))
        self.label_8.setText(_translate("Form", "力F2显示"))
